---
title: "2018 Polling Data"
author: "Molly Chiang"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(fs)
library(skimr)
library(tidyverse)

```


```{r download_data, cache = TRUE}

download.file(url = "https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "full_data.zip")

unzip("full_data.zip")

list <- dir_ls("2018-live-poll-results-master/data")

raw_data <- map_dfr(list, ~read_csv(.x, col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
)), .id = "source")

file_delete("full_data.zip")
dir_delete("2018-live-poll-results-master/")

```

```{r analysis}

clean_data <- raw_data %>%
  mutate(dem_vote = ifelse(response == "Dem", 1, 0)) %>%
  mutate(female = ifelse(gender == "Female", 1, 0)) %>%
  select(dem_vote, female, response, gender)

model <- glm(data = clean_data, formula = dem_vote ~ female, family = "binomial")

ggplot(clean_data, aes(x = female, y = dem_vote)) +
  geom_jitter(width = .1, height = .1, alpha = .04) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = FALSE)

new_data <- tibble(female = c(0,0,1))

clean_data <- clean_data %>% 
  mutate(prediction = predict(model, clean_data, type = "response"))

x <- clean_data %>% group_by(dem_vote) %>% summarize(avg = mean(prediction))

```


